---

- name: Clean AAP artifacts to a CaC format
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    cac_dir: "/tmp/filetree_output/"
  tasks:
    - name: Retrieve a repository
      ansible.scm.git_retrieve:
        origin:
          url: "{{ github_url }}"
        upstream:
          url: "{{ github_url }}"
        branch: 
          name: "{{ github_branch }}"
          duplicate_detection: false
      register: repository

    - debug: 
        var: repository

    - name: Copy CaC content to the GIT folder
      ansible.builtin.copy:
        src: "{{ cac_dir }}/"
        dest: "{{ repository['path'] }}"
        remote_src: false
        force: true
        mode: '0644'

    - name: List files matching '*.yaml'
      ansible.builtin.find:
        paths: "{{ repository['path'] }}+/"
        patterns: '*.yaml'
      register: to_remove

    - name: Remove *.yaml repo files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ to_remove.files }}"

    - name: Publish the changes
      ansible.scm.git_publish:
        commit:
          message: Cleaned CaC AAP objects
        path: "{{ repository['path'] }}"
        user:
          name: "{{ github_user }}"
          email: "{{ github_email }}"
        token: "{{ github_token }}"
