---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Get AAP node from Inventory
      ansible.builtin.set_fact:
        node_name: "{{ item }}"
      loop: "{{ groups['all'] }}"
      when: hostvars[item].tags is defined and hostvars[item].tags.Name is match("^aap-1$")

    - name: Add AAP node to the aap group
      add_host:
        name: "{{ node_name }}"
        groups: "aap"
      when: node_name is defined

- name: Extract AAP artifacts to a CaC format
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    git_repository: "github.com/carlosfparada/AAP-CaC-export.git"
    git_email: "cparada@redhat.com"
    git_username: "carlosfparada"
    controller_validate_certs: "false"
    controller_password: "{{ controller_password }}"
    output_path:	"/tmp/filetree_output"
    flatten_output: yes
  tasks:
    - name: "Get the Authentication Token for the future requests"
      ansible.builtin.uri:
        url: "https://{{ aap_fqdn }}/api/gateway/v1/tokens/"
        user: "admin"
        password: "{{ admin_password }}"
        method: POST
        force_basic_auth: true
        validate_certs: yes
        status_code: 201
      register: authtoken_res

    - name: "Set the oauth token to be used since now"
      ansible.builtin.set_fact:
        aap_oauthtoken: "{{ authtoken_res.json.token }}"
        aap_oauthtoken_url: "{{ authtoken_res.json.url }}"

    - name: Generate CaC (role filetree_create)
      ansible.builtin.import_role:
        name: infra.aap_configuration_extended.filetree_create

    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ aap_fqdn }}{{ aap_oauthtoken_url }}"
        user: "admin"
        password: "{{ admin_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: yes
        status_code: 204

    - name: Retrieve a repository
      ansible.scm.git_retrieve:
        origin:
          url: https://github.com/carlosfparada/AAP-CaC-export.git
        upstream:
          url: https://github.com/carlosfparada/AAP-CaC-export.git
        branch: 
          duplicate_detection: false
          name: main
      register: repository

    - debug: 
        var: repository

    # - name: Add to the repository
    #   ansible.builtin.copy:
    #     content: "La la"
    #     dest: "{{ repository['path'] }}/details.yaml"
    #     mode: '0644'

    - name: Publish the changes
      ansible.scm.git_publish:
        commit:
          message: Generated CaC from AAP objects
        path: "{{ repository['path'] }}"
        user:
          name: "carlosfparada"
          email: "cparada@redhat.com"
        token: "{{ github_token }}"
