---

# Credentials
controller_credentials:
  - name: "AWS AIOps Ansible Credential"
    description: "AWS AIOps Ansible Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ rhel_password }}"
      username: "{{ rhel_user }}"

# Projects
controller_projects:
  - name: "AWS AIOps Project"
    description: "AWS AIOps Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true
  - name: "AWS AIOps Fix Project"
    description: "AWS AIOps Fix Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ github_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true            

# Job Templates
controller_templates:
  - name: "AWS AIOps: 1. Deploy"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_deploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS AIOps: 2. Setup"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_setup.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Org ID
            default: "{{ org_id }}"
            variable: org_id
            type: "text"
            required: true
          - question_name: Activation Key
            default: "{{ activation_key }}"
            variable: activation_key
            type: "password"
            required: true
  - name: "AWS AIOps: 3. Unsetup"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_unsetup.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Org ID
            default: "{{ org_id }}"
            variable: org_id
            type: "text"
            required: true
          - question_name: Activation Key
            default: "{{ activation_key }}"
            variable: activation_key
            type: "password"
            required: true
  - name: "AWS AIOps: 4. Undeploy"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS AIOps: GENERATE CVE Event"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_gen_cve_event.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
  - name: "AWS AIOps: Get CVE Details"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_get_cve_details.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Lightspeed Client ID
            default: "{{ lightspeed_client_id }}"
            variable: lightspeed_client_id
            type: "password"
            required: false
          - question_name: Lightspeed Client Secret
            default: "{{ lightspeed_client_secret }}"
            variable: lightspeed_client_secret
            type: "password"
            required: false
  - name: "AWS AIOps: Get AI Code"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_get_ai_code.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: AI Endpoint
            default: "{{ ai_endpoint }}"
            variable: ai_endpoint
            type: "text"
            required: false
          - question_name: AI Model
            default: "{{ ai_model }}"
            variable: ai_model
            type: "text"
            required: false
          - question_name: AI Max Tokens
            default: "{{ ai_max_tokens }}"
            variable: ai_max_tokens
            type: "text"
            required: false
          - question_name: AI Token
            default: "{{ ai_token }}"
            variable: ai_token
            type: "password"
            required: false
  - name: "AWS AIOps: Store Code Git"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_store_code_git.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: GitHub User
            default: "{{ github_user }}"
            variable: github_user
            "type": "text"
            required: false
          - question_name: GitHub Email
            default: "{{ github_email }}"
            variable: github_email
            "type": "text"
            required: false
          - question_name: GitHub Token
            default: "{{ github_token }}"
            variable: github_token
            "type": "password"
            required: false
          - question_name: GitHub URL
            default: "{{ github_url }}"
            variable: github_url
            "type": "text"
            required: false
          - question_name: GitHub Branch
            default: "{{ github_branch }}"
            variable: github_branch
            "type": "text"
            required: false
  - name: "AWS AIOps: Check Mitigation"
    description: ""
    organization: "Default"
    project: "AWS AIOps Fix Project"
    inventory: "AWS Inventory"
    playbook: "playbook_mitigation.yml"
    verbosity: 0
    job_type: "check"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS AIOps: Run Mitigation"
    description: ""
    organization: "Default"
    project: "AWS AIOps Fix Project"
    inventory: "AWS Inventory"
    playbook: "playbook_mitigation.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS AIOps: Mitigation Workflow"
    description: "AWS AIOps: Mitigation Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "Get CVE Details"
        workflow_job_template: "AWS AIOps: Mitigation Workflow"
        unified_job_template: "AWS AIOps: Get CVE Details"
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - Get AI Code
      - identifier: "Get AI Code"
        workflow_job_template: "AWS AIOps: Mitigation Workflow"
        unified_job_template: "AWS AIOps: Get AI Code"
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - Store Code GIT
      - identifier: "Store Code GIT"
        workflow_job_template: "AWS AIOps: Mitigation Workflow"
        unified_job_template: "AWS AIOps: Store Code Git"
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - Sync Project
      - identifier: "Sync Project"
        workflow_job_template: "AWS AIOps: Mitigation Workflow"
        unified_job_template: "AWS AIOps Fix Project"
        organization: "Default"
        all_parents_must_converge: "False"
        success_nodes:
          - Check Mitigation
      - identifier: "Check Mitigation"
        workflow_job_template: "AWS AIOps: Mitigation Workflow"
        unified_job_template: "AWS AIOps: Run Mitigation"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Mitigation Approval
      - identifier: Mitigation Approval
        approval_node:
          name: Mitigation Approval
          description: Approve or not proposed Mitigation
          timeout: 300 # 2 minutes    
        success_nodes:
          - Run Mitigation
      - identifier: "Run Mitigation"
        workflow_job_template: "AWS AIOps: Mitigation Workflow"
        unified_job_template: "AWS AIOps: Run Mitigation"
        organization: "Default"
        all_parents_must_converge: "False"
    ask_variables_on_launch: true


# EDA Projects
eda_projects:
  - name: "AWS AIOps Project"
    description: "AWS AIOps Project"
    organization: "Default"
    url: "{{ project_url }}"
    tls_validation: true
    sync: true

# EDA Rulebook Activations
eda_rulebook_activations:
  - name: "AWS AIOps: Lightspeed (Insights)"
    description: "AWS AIOps: Lightspeed (Insights)"
    organization: "Default"
    project: "AWS AIOps Project"
    rulebook: lightspeed_rulebook.yml
    decision_environment: "{{ de_name }}"
    eda_credentials: "Controller Credentials"
    restart_policy: always
    enabled: true
    log_level: debug
