---

# Credentials
controller_credentials:
  - name: "AWS"
    description: "AWS"
    credential_type: "Amazon Web Services"
    organization: "Default"
    inputs:
      password: "{{ aws_access_key }}"
      username: "{{ aws_secret_key }}"
  - name: "AWS Fortinet"
    description: ""
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ admin_password }}"
      username: admin


# Projects
controller_projects:
  - name: "AWS Fortinet"
    description: "AWS Fortinet"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ registry_url }}"
    wait: true


# Inventories
controller_inventories:
  - name: "AWS"
    description: "AWS"
    organization: "Default"

controller_inventory_sources:
  - name: "AWS Source"
    description: "AWS Source"
    organization: "Default"
    source: "ec2"
    source_path: ""
    inventory: "AWS"
    update_on_launch: "True"
    overwrite: "True"
    credential: "AWS"


# # Execution Environments
# controller_execution_environments:
#   - name: "{{ ee_name }}"
#     description: ""
#     image: "{{ registry_url }}"
#     pull: "always"
#     credential: "QUAY.IO Credentials"


# Job Templates
controller_templates:
  - name: "AWS Fortinet: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "aws.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 2. Fortigate"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortigate.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
      - "AWS Fortinet"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 3. FortiAnalyzer"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortianalyzer.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
      - "AWS Fortinet"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 4. FortiManager"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortimanager.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
      - "AWS Fortinet"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 5. Fortigate Create Rules"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortigate_create_rules.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
      - "AWS Fortinet"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 5. Fortigate Create Rules Reorder"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortigate_create_rules_reorder.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
      - "AWS Fortinet"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 6 AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "aws-undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
