---

# Credentials
controller_credentials:
  - name: "AWS EDA Cisco ACI Credential"
    description: "AWS EDA Cisco ACI Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ cisco_aci_password }}"
      username: "{{ cisco_aci_user }}"

# Projects
controller_projects:
  - name: "AWS EDA Cisco ACI Project"
    description: "AWS EDA Cisco ACI Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# Job Templates
controller_templates:
  - name: "AWS EDA Cisco ACI: Compliance"
    description: ""
    organization: "Default"
    project: "AWS EDA Cisco ACI Project"
    inventory: "AWS Inventory"
    playbook: "aws_eda_compliance.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS EDA Cisco ACI Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# EDA Projects
eda_projects:
  - name: "AWS EDA Cisco ACI Project"
    description: "AWS EDA Cisco ACI Project"
    organization: "Default"
    url: "{{ project_url }}"
    tls_validation: true

# EDA Rulebook Activations
eda_rulebook_activations:
  - name: "AWS EDA Cisco ACI: Compliance"
    description: "AWS EDA Cisco ACI: Compliance"
    organization: "Default"
    project: "AWS EDA Cisco ACI Project"
    rulebook: "compliance_rulebook.yml"
    decision_environment: "{{ de_name }}"
    eda_credentials: "Controller Credentials"
    restart_policy: always
    #enabled: false
    log_level: debug