---

# Credentials
controller_credentials:
  - name: "AWS Fortinet Credential"
    description: "AWS Fortinet Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ admin_password }}"
      username: admin


# Projects
controller_projects:
  - name: "AWS Fortinet Project"
    description: "AWS Fortinet Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true


# Job Templates
controller_templates:
  - name: "AWS Fortinet: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "aws.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 2. FortiGate"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortigate.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 3. FortiAnalyzer"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortianalyzer.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 4. FortiManager"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortimanager.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 5. FortiGate Create Rules"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortigate_create_rules.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 5.1 FortiGate Create Rules Reorder"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortigate_create_rules_reorder.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 6. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "aws-undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS Fortinet: Workflow FortiGate"
    description: "AWS Fortinet: Workflow FortiGate"
    organization: "Default"
    state: "present"
    workflow_nodes:
      - identifier: "AWS Deploy"
        workflow_job_template: "AWS Fortinet: Workflow FortiGate"
        unified_job_template: "AWS Fortinet: 1. AWS Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - FortiGate Configs
      - identifier: "FortiGate Configs"
        workflow_job_template: "AWS Fortinet: Workflow FortiGate"
        unified_job_template: "AWS Fortinet: 2. FortiGate"
        organization: "Default"
        all_parents_must_converge: "False"
      #   always_nodes:
      #     - FortiGate Create Rules
      # - identifier: "FortiGate Create Rules"
      #   workflow_job_template: "AWS Fortinet: Workflow FortiGate"
      #   unified_job_template: "AWS Fortinet: 5. FortiGate Create Rules"
      #   organization: "Default"
      #   all_parents_must_converge: "False"
      #   always_nodes:
      #     - AWS Undeploy        
      # - identifier: "AWS Undeploy"
      #   workflow_job_template: "AWS Fortinet: Workflow FortiGate"
      #   unified_job_template: "AWS Fortinet: 6. AWS Undeploy"
      #   organization: "Default"
      #   all_parents_must_converge: "False"
        
  # - name: "Fortinet: workflow fortigate/analyzer/manager"
  #   description: ""
  #   organization: "Default"
  #   state: "present"
  #   simplified_workflow_nodes:
  #     - identifier: "FortiGate Configs"
  #       workflow_job_template: "Fortinet: workflow fortigate/analyzer/manager"
  #       unified_job_template: "Fortinet: 2. fortigate"
  #       organization: "Default"
  #       all_parents_must_converge: "False"
  #       always_nodes:
  #         - FortiAnalyzer Configs
  #     - identifier: "FortiManager Configs"
  #       workflow_job_template: "Fortinet: workflow fortigate/analyzer/manager"
  #       unified_job_template: "Fortinet: 4. fortimanager"
  #       organization: "Default"
  #       all_parents_must_converge: "False"
  #       always_nodes:
  #         - 67a7b785-7d0f-4fde-9b07-b4695bb7b0f5
  #     - identifier: "FortiAnalyzer Configs"
  #       workflow_job_template: "Fortinet: workflow fortigate/analyzer/manager"
  #       unified_job_template: "Fortinet: 3. fortianalyzer"
  #       organization: "Default"
  #       all_parents_must_converge: "False"
  #       always_nodes:
  #         - FortiManager Configs
  #     - identifier: "AWS Deployment"
  #       workflow_job_template: "Fortinet: workflow fortigate/analyzer/manager"
  #       unified_job_template: "Fortinet: 1.b aws"
  #       organization: "Default"
  #       all_parents_must_converge: "False"
  #       always_nodes:
  #         - FortiGate Configs
  #     - identifier: "67a7b785-7d0f-4fde-9b07-b4695bb7b0f5"
  #       workflow_job_template: "Fortinet: workflow fortigate/analyzer/manager"
  #       unified_job_template: "Fortinet: 6.b aws undeploy"
  #       organization: "Default"
  #       all_parents_must_converge: "False"
  #       always_nodes:
  #         - c13d378f-110d-4b0c-b662-5c15f5be3b46
  #     - identifier: "c13d378f-110d-4b0c-b662-5c15f5be3b46"
  #       workflow_job_template: "Fortinet: workflow fortigate/analyzer/manager"
  #       unified_job_template: "Fortinet: 6.b aws undeploy"
  #       organization: "Default"
  #       all_parents_must_converge: "False"
  #   ask_variables_on_launch: "False"
  #   allow_simultaneous: "False"
  #   scm_branch: ""
  #   webhook_service: ""
  #   notification_templates_error:
  #     - "E-mail notification"
  #   survey_enabled: False
