---

# Credentials
controller_credentials:
  - name: "AWS Netbox Credential"
    description: "AWS Netbox Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ netbox_password }}"
      username: "{{ netbox_user }}"


# Projects
controller_projects:
  - name: "AWS Netbox Project"
    description: "AWS Netbox Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true


# Job Templates
controller_templates:
  - name: "AWS Netbox: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS Netbox Project"
    inventory: "AWS Inventory"
    playbook: "aws_deploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Netbox Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Netbox: 2. Get Facts and Push"
    description: ""
    organization: "Default"
    project: "AWS Netbox Project"
    inventory: "AWS Inventory"
    playbook: "get_facts_push_netbox.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Netbox Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Netbox: 3. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS Netbox Project"
    inventory: "AWS Inventory"
    playbook: "aws_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Netbox Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS Netbox: Workflow"
    description: "AWS Netbox: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AWS Deploy"
        workflow_job_template: "AWS Netbox: Workflow"
        unified_job_template: "AWS Netbox: 1. AWS Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Netbox Config
      - identifier: "Netbox Config"
        workflow_job_template: "AWS Netbox: Workflow"
        unified_job_template: "AWS Netbox: 2. Get Facts and Push"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AWS Undeploy
      - identifier: "AWS Undeploy"
        workflow_job_template: "AWS Netbox: Workflow"
        unified_job_template: "AWS Netbox: 3. AWS Undeploy"
        organization: "Default"
        all_parents_must_converge: "False"
