---

# Credentials
controller_credentials:
  - name: "AWS AIOps Ansible Credential"
    description: "AWS AIOps Ansible Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ rhel_password }}"
      username: "{{ rhel_user }}"

# Projects
controller_projects:
  - name: "AWS AIOps Project"
    description: "AWS AIOps Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# Job Templates
controller_templates:
  - name: "AWS AIOps: Deploy"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_deploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS AIOps: Setup"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_setup.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Org ID
            default: "{{ org_id }}"
            variable: org_id
            type: "text"
            required: true
          - question_name: Activation Key
            default: "{{ activation_key }}"
            variable: activation_key
            type: "password"
            required: true
  - name: "AWS AIOps: Unsetup"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_unsetup.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Org ID
            default: "{{ org_id }}"
            variable: org_id
            type: "text"
            required: true
          - question_name: Activation Key
            default: "{{ activation_key }}"
            variable: activation_key
            type: "password"
            required: true
  - name: "AWS AIOps: Undeploy"
    description: ""
    organization: "Default"
    project: "AWS AIOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_aiops_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS AIOps Ansible Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS AIOps: Workflow"
    description: "AWS AIOps: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AIOps Deploy"
        workflow_job_template: "AWS AIOps: Workflow"
        unified_job_template: "AWS AIOps: Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AIOps Setup
      - identifier: "AIOps Setup"
        workflow_job_template: "AWS AIOps: Workflow"
        unified_job_template: "AWS AIOps: Setup"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AIOps Unsetup
      - identifier: "AIOps Unsetup"
        workflow_job_template: "AWS AIOps: Workflow"
        unified_job_template: "AWS AIOps: Unsetup"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AIOps Undeploy
      - identifier: "AIOps Undeploy"
        workflow_job_template: "AWS AIOps: Workflow"
        unified_job_template: "AWS AIOps: Undeploy"
        organization: "Default"
        all_parents_must_converge: "False"

# EDA Projects
eda_projects:
  - name: "AWS AIOps Project"
    description: "AWS AIOps Project"
    organization: "Default"
    url: "{{ project_url }}"
    tls_validation: true
    sync: true

# EDA Rulebook Activations
eda_rulebook_activations:
  - name: "AWS AIOps: XXX"
    description: "AWS AIOps: XXX"
    organization: "Default"
    project: "AWS AIOps Project"
    rulebook: lightspeed_rulebook.yml
    decision_environment: "{{ de_name }}"
    eda_credentials: "Controller Credentials"
    restart_policy: always
    enabled: true
    log_level: debug
