---

# Credentials
controller_credentials:
  - name: "AWS MCP Credential"
    description: "AWS MCP Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ mcp_password }}"
      username: "{{ mcp_user }}"

# Projects
controller_projects:
  - name: "AWS MCP Project"
    description: "AWS MCP Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# Job Templates
controller_templates:
  - name: "AWS MCP: ANSIBLE"
    description: ""
    organization: "Default"
    project: "AWS MCP Project"
    inventory: "AWS Inventory"
    playbook: "ansible.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS MCP Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS MCP: AWS"
    description: ""
    organization: "Default"
    project: "AWS MCP Project"
    inventory: "AWS Inventory"
    playbook: "aws.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS MCP Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS MCP: GITHUB"
    description: ""
    organization: "Default"
    project: "AWS MCP Project"
    inventory: "AWS Inventory"
    playbook: "github.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS MCP Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false


# Workflow Job Templates
controller_workflows:
  - name: "AWS MCP: Workflow"
    description: "AWS MCP: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "MCP ANSIBLE"
        workflow_job_template: "AWS MCP: Workflow"
        unified_job_template: "AWS MCP: ANSIBLE"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - MCP AWS
      - identifier: "MCP AWS"
        workflow_job_template: "AWS Juniper: Workflow"
        unified_job_template: "AWS MCP: AWS"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - MCP GITHUB
      - identifier: "MCP GITHUB"
        workflow_job_template: "AWS Juniper: Workflow"
        unified_job_template: "AWS MCP: GIHUB"
        organization: "Default"
        all_parents_must_converge: "False"

