---


controller_projects:
  - name: "AWS Fortinet"
    description: ""
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/carlosfparada/AWS-Fortinet.git"
    scm_update_on_launch: "True"


controller_templates:
  - name: "AWS Fortinet: 0. Controller (N/A)"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "controller.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "Vault quay.io"
    execution_environment: "CUSTOM: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 1.a VMWare Deploy (N/A)"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "vmware.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "EVE-NG Fortinet"
    execution_environment: "CUSTOM: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 1.b AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "aws.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
    execution_environment: "CUSTOM AH: Collections Supported (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 2. Fortigate"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortigate.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Fortinet"
    execution_environment: "CUSTOM AH: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 3. FortiAnalyzer"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortianalyzer.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Fortinet"
    execution_environment: "CUSTOM AH: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 4. FortiManager"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortimanager.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Fortinet"
    execution_environment: "CUSTOM AH: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 5. Fortigate Create Rules"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortigate_create_rules.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Fortinet"
    execution_environment: "CUSTOM AH: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 5. Fortigate Create Rules Reorder"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "fortigate_create_rules_reorder.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Fortinet"
    execution_environment: "CUSTOM AH: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 6.b AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "aws-undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS"
    execution_environment: "CUSTOM AH: Collections Supported (AAP2.3)"
    survey_enabled: false
  - name: "AWS Fortinet: 6.a VMWare Undeploy (N/A)"
    description: ""
    organization: "Default"
    project: "AWS Fortinet"
    inventory: "AWS"
    playbook: "vmware-undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "EVE-NG Fortinet"
    execution_environment: "CUSTOM: Collections Supported Fortinet (AAP2.3)"
    survey_enabled: false
