---

# Credentials
controller_credentials:
  - name: "Cisco Intersight Credential"
    description: "Cisco Intersight Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      username: "{{ cisco_intersight_user }}"
      password: "{{ cisco_intersight_apikeyid }}"

# Inventories
controller_inventories:
  - name: Cisco Intersight Inventory
    description: Cisco Intersight Inventory
    organization: Default

# Projects
controller_projects:
  - name: "Cisco Intersight Project"
    description: "Cisco Intersight Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# Job Templates
controller_templates:
  - name: "Cisco Intersight: 1. Create"
    description: ""
    organization: "Default"
    project: "Cisco Intersight Project"
    inventory: "Cisco Intersight Inventory"
    playbook: "create.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "Cisco Intersight Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Intersight Endpoint
            default: "{{ cisco_intersight_endpoint }}"
            variable: intersight_endpoint
            type: "text"
            required: true
          - question_name: Intersight API Key ID
            default: "{{ cisco_intersight_apikeyid }}"
            variable: intersight_apikeyid
            type: "password"
            required: true
          - question_name: Intersight Private Key
            default: "{{ cisco_intersight_privatekey }}"
            variable: intersight_privatekey
            type: "password"
            required: true
  - name: "Cisco Intersight: 2. Query"
    description: ""
    organization: "Default"
    project: "Cisco Intersight Project"
    inventory: "Cisco Intersight Inventory"
    playbook: "query.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "Cisco Intersight Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Intersight Endpoint
            default: "{{ cisco_intersight_endpoint }}"
            variable: intersight_endpoint
            type: "text"
            required: true
          - question_name: Intersight API Key ID
            default: "{{ cisco_intersight_apikeyid }}"
            variable: intersight_apikeyid
            type: "password"
            required: true
          - question_name: Intersight Private Key
            default: "{{ cisco_intersight_privatekey }}"
            variable: intersight_privatekey
            type: "password"
            required: true
  - name: "Cisco Intersight: 3. Delete"
    description: ""
    organization: "Default"
    project: "Cisco Intersight Project"
    inventory: "Cisco Intersight Inventory"
    playbook: "delete.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "Cisco Intersight Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Intersight Endpoint
            default: "{{ cisco_intersight_endpoint }}"
            variable: intersight_endpoint
            type: "text"
            required: true
          - question_name: Intersight API Key ID
            default: "{{ cisco_intersight_apikeyid }}"
            variable: intersight_apikeyid
            type: "password"
            required: true
          - question_name: Intersight Private Key
            default: "{{ cisco_intersight_privatekey }}"
            variable: intersight_privatekey
            type: "password"
            required: true

# Workflow Job Templates
controller_workflows:
  - name: "Cisco Intersight: Workflow"
    description: "Cisco Intersight: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "Cisco Intersight Create"
        workflow_job_template: "Cisco Intersight: Workflow"
        unified_job_template: "Cisco Intersight: 1. Create"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Cisco Intersight Query
      - identifier: "Cisco Intersight Query"
        workflow_job_template: "Cisco Intersight: Workflow"
        unified_job_template: "Cisco Intersight: 2. Query"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Cisco Intersight Delete
      - identifier: "Cisco Intersight Delete"
        workflow_job_template: "Cisco Intersight: Workflow"
        unified_job_template: "Cisco Intersight: 3. Delete"
        organization: "Default"
        all_parents_must_converge: "False"
