---

# Credentials
controller_credentials:
  - name: "AWS Checkpoint Credential"
    description: "AWS Checkpoint Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ checkpoint_admin_password }}"
      username: admin
  - name: "AWS Checkpoint Vault"
    description: "AWS Checkpoint Vault "
    credential_type: "Vault"
    organization: "Default"
    inputs:
      vault_password: "{{ checkpoint_vault_secret }}"

# Execution Environments
controller_execution_environments:
  - name: "{{ ee_name }}"
    description: "{{ ee_name }}"
    organization: Default
    image: "{{ ee_url }}"
    pull: always
    credential: "QUAY.IO Credentials"

# Projects
controller_projects:
  - name: "AWS Checkpoint Project"
    description: "AWS Checkpoint Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true


# Job Templates
controller_templates:
  - name: "AWS Checkpoint: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS Checkpoint Project"
    inventory: "AWS Inventory"
    playbook: "aws_checkpoint_deploy.yml"
    verbosity: 0
    job_type: "run"
    ask_skip_tags_on_launch: yes
    credentials:
      - "AWS Credential"
      - "AWS Checkpoint Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Checkpoint: 2.a Setup Checkpoint"
    description: ""
    organization: "Default"
    project: "AWS Checkpoint Project"
    inventory: "AWS Inventory"
    playbook: "aws_checkpoint_setup-checkpoint.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Checkpoint Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Checkpoint: 2.b Setup Windows"
    description: ""
    organization: "Default"
    project: "AWS Checkpoint Project"
    inventory: "AWS Inventory"
    playbook: "aws_checkpoint_setup-windows.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Checkpoint Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Checkpoint: 3. Rules Provisioning"
    description: ""
    organization: "Default"
    project: "AWS Checkpoint Project"
    inventory: "AWS Inventory"
    playbook: "aws_checkpoint_rules.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Checkpoint Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Checkpoint: 4. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS Checkpoint Project"
    inventory: "AWS Inventory"
    playbook: "aws_checkpoint_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Checkpoint Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS Checkpoint: Workflow"
    description: "AWS Checkpoint: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AWS Deploy"
        workflow_job_template: "AWS Checkpoint: Workflow"
        unified_job_template: "AWS Checkpoint: 1. AWS Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Setup Checkpoint
          - Setup Windows
      - identifier: "Setup Checkpoint"
        workflow_job_template: "AWS Checkpoint: Workflow"
        unified_job_template: "AWS Checkpoint: 2.a Setup Checkpoint"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Rules Provisioning
      - identifier: "Setup Windows"
        workflow_job_template: "AWS Checkpoint: Workflow"
        unified_job_template: "AWS Checkpoint: 2.b Setup Windows"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Rules Provisioning
      - identifier: "Rules Provisioning"
        workflow_job_template: "AWS Checkpoint: Workflow"
        unified_job_template: "AWS Checkpoint: 3. Rules Provisioning"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AWS Undeploy
      - identifier: "AWS Undeploy"
        workflow_job_template: "AWS Checkpoint: Workflow"
        unified_job_template: "AWS Checkpoint: 4. AWS Undeploy"
        organization: "Default"
        all_parents_must_converge: "False"
