---

# Credentials
controller_credentials:
  - name: "AWS Fortinet Credential"
    description: "AWS Fortinet Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ admin_password }}"
      username: admin


# Projects
controller_projects:
  - name: "AWS Fortinet Project"
    description: "AWS Fortinet Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true


# Job Templates
controller_templates:
  - name: "AWS Fortinet: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "aws.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 2. Fortigate"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortigate.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 3. FortiAnalyzer"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortianalyzer.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 4. FortiManager"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortimanager.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 5. Fortigate Create Rules"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortigate_create_rules.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 5.a Fortigate Create Rules Reorder"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "fortigate_create_rules_reorder.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Fortinet Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Fortinet: 6. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS Fortinet Project"
    inventory: "AWS Inventory"
    playbook: "aws-undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
