---

# Credentials
controller_credentials:
  - name: "AWS GitOps Credential"
    description: "AWS GitOps Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ gitops_password }}"
      username: "{{ gitops_user }}"
  - name: "AWS GitOps Vault"
    description: "AWS GitOps Vault"
    credential_type: "Vault"
    organization: "Default"
    inputs:
      vault_password: "{{ gitops_vault_secret }}"
  # - name: "GitOps Credential"
  #   description: "GitOps Credential"
  #   credential_type: "Machine"
  #   organization: "Default"
  #   inputs:
  #     password: "{{ gitops_password }}"
  #     username: "admin"

# Projects
controller_projects:
  - name: "AWS GitOps Project"
    description: "AWS GitOps Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# # Inventories
# controller_inventories:
#   - name: "GitOps Inventory"
#     description: "GitOps Inventory"
#     organization: "Default"

# # Inventory Sources
# controller_inventory_sources:
#   - name: GitOps Inventory Source
#     description: GitOps Inventory Source
#     #organization: Default
#     source: 'scm'
#     source_project: "AWS GitOps Project"
#     source_path: "aws_hosts.yml"
#     credential: GitOps Credential
#     inventory: GitOps Inventory
#     execution_environment: "{{ ee_name }}"
#     update_on_launch: True
#     update_cache_timeout: 0
#     overwrite: True
#     overwrite_vars: True
#     source_vars:
#       GITOPS_API: "http://gitops_url:8000"
#       GITOPS_TOKEN: "gitops_token"

# Job Templates
controller_templates:
  - name: "AWS GitOps: 01. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_deploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 02. Setup"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_setup.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
      - "AWS GitOps Vault"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 03. Ping"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_ping.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 04. Facts"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_facts.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 05. Show"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_show.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false    
  - name: "AWS GitOps: 06. Show Survey"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_show_survey.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false  
  - name: "AWS GitOps: 07. VLAN Survey"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_vlan_survey.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: VLAN Name
            default: Vlan100
            variable: vlan_name
            type: "text"
            required: true
          - question_name: VLAN Id
            default: "100"
            variable: vlan_id
            type: "text"
            required: true
          - question_name: VLAN State
            default: "active"
            variable: vlan_state
            type: "multiplechoice"
            choices: "active\nsuspend"
            required: true
          - question_name: VLAN Operation
            default: "merged"
            variable: vlan_oper
            type: "multiplechoice"
            choices: "merged\noverridden\ndeleted"
            required: true
  - name: "AWS GitOps: 08. VLAN"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_vlan.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 09. IP"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_ip.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 10. BGP"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_bgp.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS GitOps: 11. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS GitOps Project"
    inventory: "AWS Inventory"
    playbook: "aws_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS GitOps Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS GitOps: Workflow"
    description: "AWS GitOps: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AWS Deploy"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 01. AWS Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps Setup
      - identifier: "GitOps Setup"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 02. Setup"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps Ping
      - identifier: "GitOps Ping"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 03. Ping"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps Facts
      - identifier: "GitOps Facts"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 04. Facts"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps Show
      - identifier: "GitOps Show"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 05. Show"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps Show Survey
      - identifier: "GitOps Show Survey"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 06. Show Survey"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps VLAN Survey
      - identifier: "GitOps VLAN Survey"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 07. VLAN Survey"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps VLAN
      - identifier: "GitOps VLAN"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 08. VLAN"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps IP
      - identifier: "GitOps IP"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 09. IP"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - GitOps BGP
      - identifier: "GitOps BGP"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 10. BGP"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AWS Undeploy
      - identifier: "AWS Undeploy"
        workflow_job_template: "AWS GitOps: Workflow"
        unified_job_template: "AWS GitOps: 11. AWS Undeploy"
        organization: "Default"
        all_parents_must_converge: "False"

# EDA Projects
eda_projects:
  - name: "AWS EDA GitOps Project"
    description: "AWS EDA GitOps Project"
    organization: "Default"
    url: "{{ project_url }}"
    tls_validation: true

# # EDA Rulebook Activations
# eda_rulebook_activations:
#   - name: "AWS EDA GitOps: Config Context"
#     description: "AWS EDA GitOps: Config Context"
#     organization: "Default"
#     project: "AWS EDA GitOps Project"
#     rulebook: "config_context_rulebook.yml"
#     decision_environment: "{{ de_name }}"
#     eda_credentials: "Controller Credentials"
#     restart_policy: always
#     #enabled: false
#     log_level: debug