---

# Credentials
controller_credentials:
  - name: "AWS RHEL Credential"
    description: "AWS RHEL Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ rhel_password }}"
      username: "{{ rhel_user }}"


# Projects
controller_projects:
  - name: "AWS RHEL Project"
    description: "AWS RHEL Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true
  # RHTOUR: TO REMOVE
  - name: "AWS RHEL RHTOUR Project"
    description: "AWS RHEL Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "https://github.com/naarh/RHTour.git"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# Job Templates
controller_templates:
  - name: "AWS RHEL: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS RHEL Project"
    inventory: "AWS Inventory"
    playbook: "aws_deploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS RHEL Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS RHEL: 2. Config"
    description: ""
    organization: "Default"
    project: "AWS RHEL Project"
    inventory: "AWS Inventory"
    playbook: "rhel.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS RHEL Credential"
    execution_environment: "{{ ee_name }}"
    # extra_vars:
    #   subscription_user: "{{ subscription_user }}"
    #   subscription_pass: "{{ subscription_pass }}"
    #   rh_subs_pool_id: "{{ rh_subs_pool_id }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Subscription User
            default: "{{ subscription_user }}"
            variable: subscription_user
            "type": "text"
          - question_name: Subscription Password
            default: "{{ subscription_pass }}"
            variable: subscription_pass
            "type": "password"
          - question_name: Subscription Pool Id
            default: "{{ rh_subs_pool_id }}"
            variable: rh_subs_pool_id
            "type": "password"

  - name: "AWS RHEL: 3. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS RHEL Project"
    inventory: "AWS Inventory"
    playbook: "aws_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS RHEL Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  # RHTOUR: TO REMOVE
  - name: "AWS RHEL: RHTOUR Lightspeed"
    description: ""
    organization: "Default"
    project: "AWS RHEL RHTOUR Project"
    inventory: "AWS Inventory"
    playbook: "RHEL9.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS RHEL Credential"
    execution_environment: "{{ ee_name }}"
    # extra_vars:
    #   subscription_user: "{{ subscription_user }}"
    #   subscription_pass: "{{ subscription_pass }}"
    #   rh_subs_pool_id: "{{ rh_subs_pool_id }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Subscription User
            default: "{{ subscription_user }}"
            variable: subscription_user
            "type": "text"
          - question_name: Subscription Password
            default: "{{ subscription_pass }}"
            variable: subscription_pass
            "type": "password"
          - question_name: Subscription Pool Id
            default: "{{ rh_subs_pool_id }}"
            variable: rh_subs_pool_id
            "type": "password"

  # RHTOUR: TO REMOVE
  - name: "AWS RHEL: RHTOUR Lightspeed backup"
    description: ""
    organization: "Default"
    project: "AWS RHEL RHTOUR Project"
    inventory: "AWS Inventory"
    #playbook: "RHEL9-backup.yml"
    playbook: "RHEL9.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS RHEL Credential"
    execution_environment: "{{ ee_name }}"
    become_enabled: true
    # extra_vars:
    #   subscription_user: "{{ subscription_user }}"
    #   subscription_pass: "{{ subscription_pass }}"
    #   rh_subs_pool_id: "{{ rh_subs_pool_id }}"
    survey_enabled: true
    survey:
        name: Survey
        description: Survey
        spec:
          - question_name: Subscription User
            default: "{{ subscription_user }}"
            variable: subscription_user
            "type": "text"
          - question_name: Subscription Password
            default: "{{ subscription_pass }}"
            variable: subscription_pass
            "type": "password"
          - question_name: Subscription Pool Id
            default: "{{ rh_subs_pool_id }}"
            variable: rh_subs_pool_id
            "type": "password"

# Workflow Job Templates
controller_workflows:
  - name: "AWS RHEL: Workflow"
    description: "AWS RHEL: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AWS Deploy"
        workflow_job_template: "AWS RHEL: Workflow"
        unified_job_template: "AWS RHEL: 1. AWS Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - RHEL Config
      - identifier: "RHEL Config"
        workflow_job_template: "AWS RHEL: Workflow"
        unified_job_template: "AWS RHEL: 2. Config"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AWS Undeploy
      - identifier: "AWS Undeploy"
        workflow_job_template: "AWS RHEL: Workflow"
        unified_job_template: "AWS RHEL: 3. AWS Undeploy"
        organization: "Default"
        all_parents_must_converge: "False"
