---

# Credentials


# Projects
controller_projects:
  - name: "AWS Networking Project"
    description: "AWS Networking Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true


# Job Templates
controller_templates:
  - name: "AWS Networking: 1. VPC Peering"
    description: ""
    organization: "Default"
    project: "AWS Networking Project"
    inventory: "AWS Inventory"
    playbook: "aws_vpc_peering.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Networking: 2. VPC Peering Delete"
    description: ""
    organization: "Default"
    project: "AWS Networking Project"
    inventory: "AWS Inventory"
    playbook: "aws_vpc_peering_delete.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Networking: 3. VPC Transit"
    description: ""
    organization: "Default"
    project: "AWS Networking Project"
    inventory: "AWS Inventory"
    playbook: "aws_vpc_transit.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS Networking: 4. VPC Transit Delete"
    description: ""
    organization: "Default"
    project: "AWS Networking Project"
    inventory: "AWS Inventory"
    playbook: "aws_vpc_transit_delete.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS Networking: Workflow"
    description: "AWS Networking: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AWS VPC Peering"
        workflow_job_template: "AWS Networking: Workflow"
        unified_job_template: "AWS Networking: 1. VPC Peering"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Networking VPC Peering Delete
      - identifier: "Networking VPC Peering Delete"
        workflow_job_template: "AWS Networking: Workflow"
        unified_job_template: "AWS Networking: 2. VPC Peering Delete"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Networking VPC Transit
      - identifier: "Networking VPC Transit"
        workflow_job_template: "AWS Networking: Workflow"
        unified_job_template: "AWS Networking: 3. VPC Transit"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Networking VPC Transit Delete
      - identifier: "Networking VPC Transit Delete"
        workflow_job_template: "AWS Networking: Workflow"
        unified_job_template: "AWS Networking: 4. VPC Transit Delete"
        organization: "Default"
        all_parents_must_converge: "False"
