---

# Credentials
controller_credentials:
  - name: "AWS Paloalto Credential"
    description: "AWS Paloalto Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      password: "{{ paloalto_admin_password }}"
      username: admin
  - name: "AWS Paloalto Vault"
    description: "AWS Paloalto Vault "
    credential_type: "Vault"
    organization: "Default"
    inputs:
      vault_password: "{{ paloalto_vault_secret }}"

# Projects
controller_projects:
  - name: "AWS EDA Paloalto Project"
    description: "AWS EDA Paloalto Project"
    organization: "Default"
    scm_type: "git"
    scm_url: "{{ project_url }}"
    scm_update_on_launch: "True"
    execution_environment: "{{ ee_name }}"
    wait: true

# Job Templates
controller_templates:
  - name: "AWS EDA Paloalto: 1. AWS Deploy"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_deploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Paloalto Credential"
      - "AWS Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: 2. Set Password"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_setpass.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
      - "AWS Paloalto Vault"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: 3. Setup"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_setup.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: 4. Rules Provisioning"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_rule_provision.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: 5. Rules Delete"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_rule_delete.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: 6. Setup Delete"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_setup_delete.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: 7. AWS Undeploy"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_undeploy.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: Fix Compliance Log"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_compliance_log.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false
  - name: "AWS EDA Paloalto: Fix Compliance Tag"
    description: ""
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    inventory: "AWS Inventory"
    playbook: "aws_paloalto_compliance_tag.yml"
    verbosity: 0
    job_type: "run"
    credentials:
      - "AWS Credential"
      - "AWS Paloalto Credential"
    execution_environment: "{{ ee_name }}"
    survey_enabled: false

# Workflow Job Templates
controller_workflows:
  - name: "AWS EDA Paloalto: Workflow"
    description: "AWS EDA Paloalto: Workflow"
    organization: "Default"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "AWS Deploy"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 1. AWS Deploy"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Paloalto Set Password
      - identifier: "Paloalto Set Password"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 2. Set Password"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Paloalto Setup
      - identifier: "Paloalto Setup"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 3. Setup"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Paloalto Rules Provisioning
      - identifier: "Paloalto Rules Provisioning"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 4. Rules Provisioning"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Paloalto Rules Delete
      - identifier: "Paloalto Rules Delete"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 5. Rules Delete"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - Paloalto Setup Delete
      - identifier: "Paloalto Setup Delete"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 6. Setup Delete"
        organization: "Default"
        all_parents_must_converge: "False"
        always_nodes:
          - AWS Undeploy        
      - identifier: "AWS Undeploy"
        workflow_job_template: "AWS EDA Paloalto: Workflow"
        unified_job_template: "AWS EDA Paloalto: 7. AWS Undeploy"
        organization: "Default"
        all_parents_must_converge: "False"

# EDA Credentials
# eda_controller_tokens:
#   - name: "Controller Token"
#     description: "Controller Token"
#     token: MISSING

# EDA Credentials
eda_credentials:
  - name: "QUAY.IO Credentials"
    description: "QUAY.IO Credentials"
    credential_type: "Container Registry"
    organization: Default
    inputs:
      host: quay.io
      username: "{{ quay_username }}"
      password: "{{ quay_password }}"
      verify_ssl: true
  - name: "Controller Credentials"
    description: "Controller Credentials"
    credential_type: "Red Hat Ansible Automation Platform"
    organization: Default
    inputs:
      host: "{{ groups['aap'][0] }}"
      username: "admin"
      password: "{{ admin_password }}"
      verify_ssl: false

# EDA Decision Environment
eda_decision_environments:
  - name: "{{ de_name }}"
    description: "{{ de_name }}"
    organization: "Default"
    image_url: "{{ de_url }}"
    credential: QUAY.IO Credentials

# EDA Projects
eda_projects:
  - name: "AWS EDA Paloalto Project"
    description: "AWS EDA Paloalto Project"
    organization: "Default"
    url: "{{ project_url }}"
    tls_validation: true

# EDA Rulebook Activations
eda_rulebook_activations:
  - name: "AWS EDA Paloalto: Config Compliance"
    description: "AWS EDA Paloalto: Config Compliance"
    organization: "Default"
    project: "AWS EDA Paloalto Project"
    rulebook: config_rulebook.yml
    decision_environment: "{{ de_name }}"
    eda_credentials: "Controller Credentials"
    enabled: false
    log_level: debug

